// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "7fb7dbcee11b721d7ffae518e2ebfc82"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"6e0716d0cbb904e2ba1ade15e29261dd": "1f8b08000000000000ffb2c928c9cdb1e3e552505050b049ca4fa984b2c1fc0c433bc794dccc3c1bfd0c433b5e2e844c7575496a6e414e6249aa8252727e5e496a5e8992825e6d2dd41c7da84136fa60d301010000ffffcb4289a764000000",
		"ad0c047325e4a93f0c1877e6db61511b": "1f8b08000000000000ffaaae4e494dcbcc4b55504acecf2b49cd2b51aaade5e552505050a8cce7e5aaae4ecd4ba9ad05040000ffffeacd5d9c25000000",
		"f100e2b3cf9b95783759d346681ea080": "1f8b08000000000000ffaaae4e494dcbcc4b55504acecf2b49cd2b51aaade5aaae4ecd4ba9ad05040000ffffcdf6b0541c000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("Templates", "./templates")
		b.SetResolver("admin/index.gohtml", packr.Pointer{ForwardBox: gk, ForwardPath: "ad0c047325e4a93f0c1877e6db61511b"})
		b.SetResolver("admin/layout.gohtml", packr.Pointer{ForwardBox: gk, ForwardPath: "6e0716d0cbb904e2ba1ade15e29261dd"})
		b.SetResolver("admin/login.gohtml", packr.Pointer{ForwardBox: gk, ForwardPath: "f100e2b3cf9b95783759d346681ea080"})
	}()
	return nil
}()
